### ISSUE TITLE
NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by KamilLelonek** [middleman/middleman-autoprefixer#15]
```
NoMethodError: undefined method `split' for nil:NilClass
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/middleman-autoprefixer-2.4.2/lib/middleman-autoprefixer/extension.rb:45:in `call'
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/Users/squixy/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/Users/squixy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/squixy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/squixy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by porada** [comment]
Could you paste your `Gemfile`? Is this happening with `middleman` 4?

**Comment by KamilLelonek** [comment]
Nope, a lots of things don't work with Middleman 4 so I'm not using it yet.

```
    middleman (3.3.7)
      coffee-script (~> 2.2)
      compass (>= 1.0.0, < 2.0.0)
      compass-import-once (= 1.0.5)
      execjs (~> 2.0)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-core (= 3.3.7)
      middleman-sprockets (>= 3.1.2)
      sass (>= 3.4.0, < 4.0)
      uglifier (~> 2.5)
    middleman-autoprefixer (2.4.2)
      autoprefixer-rails (~> 5.1.0)
      middleman-core (>= 3.3.3)
```

**Comment by KamilLelonek** [comment]
It happens because of https://github.com/middleman/middleman-autoprefixer/commit/0259f487b1b3346860a45429b34832773d9a3ede especially in https://github.com/middleman/middleman-autoprefixer/blob/0259f487b1b3346860a45429b34832773d9a3ede/lib/middleman-autoprefixer/extension.rb#L45. There's no `'Content-Type'` in `headers`.

**Comment by porada** [comment]
Good catch. Could you make a pull request with the fix?

**Comment by KamilLelonek** [comment]
Done.

**Comment by porada** [comment]
Thanks a lot! Releasing the fix in a few moments.

**Comment by seemahari** [comment]
Facing a similar issue now @porada @KamilLelonek Any idea what I can do? 

NoMethodError: undefined method `split' for nil:NilClass
	/Users/seema/docs/lib/multilang.rb:3:in `block_code'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/renderers/redcarpet.rb:51:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/renderers/redcarpet.rb:51:in `evaluate'
	/usr/local/lib/ruby/gems/2.4.0/gems/tilt-2.0.6/lib/tilt/template.rb:100:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/file_renderer.rb:79:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/template_context.rb:202:in `_render_with_all_renderers'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/template_context.rb:188:in `render_file'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/template_context.rb:119:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/usr/local/lib/ruby/gems/2.4.0/gems/padrino-helpers-0.13.3.3/lib/padrino-helpers/render_helpers.rb:55:in `block in partial'
	/usr/local/lib/ruby/gems/2.4.0/gems/padrino-helpers-0.13.3.3/lib/padrino-helpers/render_helpers.rb:48:in `each'
	/usr/local/lib/ruby/gems/2.4.0/gems/padrino-helpers-0.13.3.3/lib/padrino-helpers/render_helpers.rb:48:in `each_with_object'
	/usr/local/lib/ruby/gems/2.4.0/gems/padrino-helpers-0.13.3.3/lib/padrino-helpers/render_helpers.rb:48:in `partial'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/default_helpers.rb:287:in `partial'
	layouts/layout.erb:316:in `block (2 levels) in singleton class'
	layouts/layout.erb:315:in `each'
	layouts/layout.erb:315:in `block in singleton class'
	layouts/layout.erb:-8:in `instance_eval'
	layouts/layout.erb:-8:in `singleton class'
	layouts/layout.erb:-10:in `__tilt_70212806988920'
	/usr/local/lib/ruby/gems/2.4.0/gems/tilt-2.0.6/lib/tilt/template.rb:161:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/tilt-2.0.6/lib/tilt/template.rb:161:in `evaluate'
	/usr/local/lib/ruby/gems/2.4.0/gems/tilt-2.0.6/lib/tilt/template.rb:100:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/file_renderer.rb:79:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/template_renderer.rb:157:in `block in render'
	/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/util.rb:21:in `instrument'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/template_renderer.rb:156:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/sitemap/resource.rb:154:in `render'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	/usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/rack.rb:112:in `process_request'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/rack.rb:66:in `block in call'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/rack.rb:65:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/rack.rb:65:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-autoprefixer-2.7.1/lib/middleman-autoprefixer/extension.rb:48:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/inline_url_rewriter.rb:74:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
	/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'


This is my gemfile:

gem 'middleman', '~>4.2.1'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem "middleman-sprockets", "~> 4.1.0"
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'


Multilang.rb:
module Multilang
  def block_code(code, full_lang_name)
    parts = full_lang_name.split('--')
    rouge_lang_name = parts[0] || ""
    super(code, rouge_lang_name).sub("highlight #{rouge_lang_name}") do |match|
      match + " tab-" + full_lang_name
    end
  end
end

require 'middleman-core/renderers/redcarpet'
Middleman::Renderers::MiddlemanRedcarpetHTML.send :include, Multilang
