### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman-autoprefixer#18]
I'd really like a `CHANGELOG.md` for this extension so that I can quickly understand what's changed in new versions.

**Comment by porada** [comment]
Is this issue only about the format? Because I’ve been documenting changes in the [release notes](https://github.com/middleman/middleman-autoprefixer/releases) since the very first version.

**Comment by bhollis** [comment]
Oh, I hadn't seen that. All of the other middleman projects have a `CHANGELOG.md`.

**Comment by porada** [comment]
It’s probably a good idea to maintain some kind of consistency throughout the organization—I’ll take care of the log by the next release. :ok_hand:
