### ISSUE TITLE
middleman-autoprefixer 2.6.0 not prefixing

### ISSUE THREAD

**Issue by sebastiangraz** [middleman/middleman-autoprefixer#21]
No prefixes are made at all. I have tried on gradients and on flex elements.

This is on a clean slate new middleman build without any alterations:

Running bundle install gives me

    ...
    Using middleman-autoprefixer 2.6.0
    ...

Gemfile

    # If you do not have OpenSSL installed, update
    # the following line to use "http://" instead
    source 'https://rubygems.org'

    gem "middleman", "~>3.3.12"

    gem 'middleman-autoprefixer'

     # Live-reloading plugin
    gem "middleman-livereload", "~> 3.1.0"

    # For faster file watcher updates on Windows:
    gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

    # Windows does not come with time zone data
    gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]

config.rb

    configure :development do
        activate :livereload
        activate :autoprefixer
    end

Appreciate any help :)

**Comment by porada** [comment]
Could you try locking the previous version, `2.5.0`, and see if it works?

**Comment by tdreyno** [comment]
I think I saw this too. When I added a browser list, it started working

**Comment by tdreyno** [comment]
Maybe we are in the future and there are no prefixes for the default autoprefixer query?

**Comment by sebastiangraz** [comment]
I tested both ````2.5.0```` and ````2.4.3````and it doesn't budge.

**Comment by porada** [comment]
@sebastiangraz, could you test your stylesheets again the current `master`? I think I squashed the bug.

```ruby
gem 'middleman-autoprefixer', github: 'middleman/middleman-autoprefixer'
```

Once it’s confirmed, I’ll release a version with the fix.

**Comment by sebastiangraz** [comment]
Yep that worked :+1:

**Comment by porada** [comment]
:stars: `v2.6.1`
