### ISSUE TITLE
Re-enable Gemnasium hook

### ISSUE THREAD

**Issue by porada** [middleman/middleman-autoprefixer#22]
For some reason, Gemnasium refresh has to be trigged manually after each `git push`.

@tdreyno or @bhollis, could you re-enable the Gemnasium hook [in the settings](https://github.com/middleman/middleman-autoprefixer/settings/hooks) or give me admin access to this repository so that I could do it myself?

**Comment by tdreyno** [comment]
Made you admin

**Comment by porada** [comment]
Thank you. :cocktail:
