### ISSUE TITLE
Middleman Init not working, new Middleman Install Windows

### ISSUE THREAD

**Issue by trejster** [middleman/middleman-autoprefixer#23]
I have installed the latest version of ruby 2.2.3 and the associated dev kit which all installed successfully on a windows 8 pc. Installed middleman which installed successfully. Now on running middleman init I am getting an error: 

"c:/Ruby22/bin/middleman:23 in 'load': cannot load such file -- C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/bin/middleman (LoadError).."

Can anyone help please?

Looking in the quoted directory there is no bin directory underneath middleman-core-4.0.0?

**Comment by tdreyno** [comment]
Can you post this in the main Middleman repo please: https://github.com/middleman/middleman

**Comment by trejster** [comment]
Sorry I thought I had done, will do

**Comment by jawwadzafar** [comment]
you can use this template:

https://github.com/jawwadzafar/middleman-boilerplate.git
