### ISSUE TITLE
Comments are parsed despite being commented

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman-autoprefixer#29]
Have the following bits

```
/*@mixin prefix($prop, $val) {
	@each $prefix in '-webkit-', '-moz-', '-ms-', '' {
		//#{$prefix}#{$prop}: $val;
	}
}*/
```

But on rendering the site I get an error similar to this

`Error: Undefined variable: $prefix on line 24`

As the comment is commented, I would have expected the code to run through without exceptions.

**Comment by porada** [comment]
Hey @andreamoro, this isn’t any fault of the extension.

You’re probably getting this error because you incorrectly wrapped the mixin with a `/* CSS comment */`. This is the Sass way:

```scss
// @mixin prefix($prop, $val) {
//   @each $prefix in '-webkit-', '-moz-', '-ms-', '' {
//     #{$prefix}#{$prop}: $val;
//   }
// }
```
