### ISSUE TITLE
Is newest middleman-autoprefixer compatible with css grid??

### ISSUE THREAD

**Issue by riiino** [middleman/middleman-autoprefixer#32]
I use autoprefixer with middleman. and I heard that now autoprefixer is compatible with css grid property and it need to be activated by adding "grid: true" or something.
but I'm not sure how. How should I write??

Here is my setting for autoprefixer in config.rb,

```
-------------------------------------------
activate :autoprefixer do |config|
  config.browsers = ['last 2 versions']
end
--------------------------------------------
```

**Comment by Calvett** [comment]
No, that i know but you can add it yourself. 
ruby-2.4.1/gems/middleman-autoprefixer-2.9.0/lib/middleman-autoprefixer/extension.rb
Add this behind line "option :browsers, nil,   'Supported browsers'"
**option :grid, true,   'Supported grid'**
And then in:
@processor = ::AutoprefixerRails::Processor.new({
            browsers: options[:browsers] && Array(options[:browsers]),
            **grid:      options[:grid],**
            add:      options[:add],
            remove:   options[:remove],
            cascade:  options[:cascade]
          })
And in your config.rb file:

activate :autoprefixer do |prefix|
  prefix.browsers = ['last 2 versions', 'Explorer >= 9']
  prefix.grid = true
end

And there you have grid support ;)

**Comment by riiinoj** [comment]
Thank you so much!
It worked. 
I really hope that middleman-autoprefixer will compatible with css grid soon.

**Comment by tdreyno** [comment]
@Calvett Seems like a pretty straightforward PR that could be made to this repo. Are there other new Autoprefixer options that we're not forwarding?

**Comment by bunnymatic** [comment]
Not sure how much of this is related but https://github.com/ai/autoprefixer-rails/issues/194 just fixed an issue that was causing issues around `grid-template-columns: 1fr 1fr 1fr 1fr;`, so if https://github.com/middleman/middleman-autoprefixer/pull/39 get's merged, you may find the support for grids will be restored.
