### ISSUE TITLE
autoprefixer-rails deprecated

### ISSUE THREAD

**Issue by noraj** [middleman/middleman-autoprefixer#38]
[autoprefixer-rails](https://github.com/ai/autoprefixer-rails) was deprecated: https://github.com/ai/autoprefixer-rails/wiki/Deprecated

Also autoprefixer-rails 9.8.6.2 seems to bring some errors (https://github.com/ai/autoprefixer-rails/issues/174)

**Comment by JoshuaWoodsdev** [comment]
Well I'm stuck. I'm a newbie and don't know enough JS to do that..... Is autoprefixer the only backend choice?...JS is doing too much :(

**Comment by tdreyno** [comment]
Yeah, bummed by this too.

Still, deprecated should still work. Are you seeing bugs in an older app? We might be able to lock down some versioning to preserve the old behavior.

**Comment by noraj** [comment]
Will be fixed in 9.8.6.3 so no need to fix a version.

**Comment by JoshuaWoodsdev** [comment]
I just started using Github this is amazing. I had trouble with middleman, but seems like it still works.... It will be a bit before I know enough JS. I've been in Ruby world! ha

**Comment by noraj** [comment]
9.8.6.3 was released and it's working again.
