### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by judewang** [middleman/middleman-autoprefixer#9]
Hi, my name is Jude.

I found that using Middleman v3.3.3 with middleman-autoprefixer v2.1.0 will an issue that make browser failing to load stylesheet after refreshing the page. It sent a message said "Failed to load resource: the server responded with a status of 500 (Internal Server Error) " to  browser's console window. I have tested this with middleman-autoprefixer v2.0.1 and it was OK. I think the issue will be produce only when using v2.1.0.

Thanks.

**Comment by srjkrl20011991** [comment]
I am new in angular ... getting error 
CREATE UserApp/e2e/tsconfig.e2e.json (213 bytes)
npm ERR! code E500
npm ERR! 500 Internal Server Error: autoprefixer@^8.4.1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\suraj.karale\AppData\Roaming\npm-cache\_logs\2018-07-03T06_16_43_259Z-debug.log
Package install failed, see above.


Version Details -

Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.0
typescript                   2.7.2
